PULP_APP = ourtest
PULP_APP_FC_SRCS = ourtest.c bdac.c classify.c rythmchk.c noisechk.c match.c postclas.c analbeat.c qrsfilt.c qrsdet.c
#PULP_APP_HOST_SRCS = test.c
PULP_CFLAGS = -O3 -g

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk
